from pathlib import Path

# Paths
OUTPUTS_DIR_PATH = Path(".")

# Patches
PATCH_RESOLUTION_TOLERANCE = 1.5
PATCH_BACKGROUND_ANGLE = 75
PATCH_OUTLIER_SIGMA = 5
MIN_PATCH_DENSITY = -1
NUM_PATCH_DENSITY_BINS = -1
MIN_PATCH_BIN_DENSITY = -1
PATCH_INTERPOLATION_METHOD = "nearest"
PATCH_IMAGE_FORMAT = "png"

# Misc
DOWNLOAD_CHUNK_SIZE = 67_108_864  # 64 MB
DATETIME_FORMAT = r"%Y-%m-%d_%H-%M-%S"
LOGGING_FORMAT = r"%(asctime)s - %(levelname)s - %(message)s"
JSON_INDENT = 4
